### ISSUE TITLE
Parallels: booting helloSystem with and without EFI

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/docs#18]
Maybe something for https://github.com/helloSystem/hello/wiki

From <https://old.reddit.com/r/freebsd/comments/l0r28f/-/gnko58t/?context=2>

> `vm.bios.efi = 1`
> 
> in the parallels boot order setting, under 'Advanced Settings.'

**Comment by probonopd** [comment]
Has anyone ever managed to boot helloSystem in Parallels? And does helloSystem behave better in Parallels when EFI is on? Or is all of this just speculation at this point?

**Comment by grahamperrin** [comment]
> Has anyone ever managed to boot helloSystem in Parallels? And does helloSystem behave better in Parallels when EFI is on? …

Probably "Yes" to both questions; please see the linked commentary.

**Comment by probonopd** [comment]
Ah ok, had overlooked that. Thank you.

**Comment by probonopd** [comment]
Added to the documentation. Thank you very much.
