### ISSUE TITLE
index page is rendering the wrong img src of screenshot

### ISSUE THREAD

**Issue by sapeol** [helloSystem/docs#36]
hey just noticed a small issue, 

src for the screenshot should be 

`https://raw.githubusercontent.com/helloSystem/hello/master/screenshots/20211219-desktop-0.7.png`

instead of `https://github.com/helloSystem/hello/blob/master/screenshots/20211219-desktop-0.7.png`

**Comment by probonopd** [comment]
Let's hope that this fixes it. Thanks @sapeol
