### ISSUE TITLE
EPUB table of contents defective

### ISSUE THREAD

**Issue by probonopd** [helloSystem/docs#4]
In Calibre and other EPUB rendering systems the table of contents is empty besides one single entry, "hello":

![image](https://user-images.githubusercontent.com/2480569/100674600-b2d5c680-3365-11eb-82c1-83a12e5f9370.png)

cc @TheAssassin

**Comment by TheAssassin** [comment]
After a short analysis, I blame your mixing of Markdown and reST. I've never seen anything like this happen before with regular sphinx docs.

**Comment by probonopd** [comment]
Possibly related to the way we do our toctrees.

See https://ocrmypdf.readthedocs.io/en/latest/ for a repo that also has multiple ones, but possible done in the correct way?

**Comment by TheAssassin** [comment]
That page uses reST, like everyone else does with Sphinx. The reason is it works and provides access to all features. Go switch to reST and it'll work.

**Comment by probonopd** [comment]
It is working now. (Kaum macht mer's richtig, scho geht's.)
