### ISSUE TITLE
Replace recommonmark in favor of MyST-Parser

### ISSUE THREAD

**Issue by probonopd** [helloSystem/docs#42]
Sooner or later we may have to go through the hassle of replacing recommonmark in favor of MyST-Parser.
https://github.com/readthedocs/recommonmark/issues/221

Since I dread this type of maintenance chores of what previously was a working system, I'd happily accept a pull request.

**Comment by Sporiff** [comment]
I recently went through this for the Funkwhale documentation as we migrated from rST to MyST. I would also recommend looking into using [Sphinx design](https://sphinx-design.readthedocs.io/en/rtd-theme/) to get some really powerful features like tabbed code blocks etc.

I'm happy to take a look at this at some point.
