### ISSUE TITLE
Wiki-typo

### ISSUE THREAD

**Issue by NitroNils** [helloSystem/docs#45]
Hello!

I didn't find sources for the wiki, so issuing this here:

A typo in this section:

https://github.com/helloSystem/hello/wiki#gnustep

`s/ramework/framework`

**Comment by probonopd** [comment]
Thanks @NitroNils, fixed. There is an "Edit" button in the upper-right corner of each Wiki page.

**Comment by NitroNils** [comment]
That's perfect, missed it.
Thanks :)
