### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/docs#8]
https://hellosystem.github.io/docs/search.html?q=Python&check_keywords=yes&area=default for example: 

![image](https://user-images.githubusercontent.com/192271/103366454-9c34a380-4aba-11eb-909e-9bcdc2e1efb2.png)

**Comment by probonopd** [comment]
I can reproduce this issue but do not know what might be causing this.

**Comment by probonopd** [comment]
Does it work for you on https://docs.appimage.org/?
Might adblockers possibly interfere with the search funktion?

**Comment by grahamperrin** [comment]
Good thinking. 

https://hellosystem.github.io/docs/search.html?q=Python&check_keywords=yes&area=default tested first in Firefox with extensions, then with [surf](https://surf.suckless.org/) (screenshot above), then with a separate Firefox profile in safe mode i.e. 

`firefox -P test --safe-mode 'https://hellosystem.github.io/docs/search.html?q=Python&check_keywords=yes&area=default'

– with the same result. No better after disabling standard tracking protection. 

https://docs.appimage.org/search.html?q=Python&check_keywords=yes&area=default also endlessly searching with Firefox in safe mode. 

So, not specific to helloSystem/docs

**Comment by probonopd** [comment]
Any idea @TheAssassin?

**Comment by probonopd** [comment]
Not even https://pybsd.readthedocs.io/en/latest/search.html?q=install&check_keywords=yes&area=default seems to work for me.

**Comment by grahamperrin** [comment]
+1

For that URL, the same here with surf.

**Comment by grahamperrin** [comment]
No longer reproducible.

**Comment by probonopd** [comment]
Gotta love bugs that fix themselves :+1:
